Revert "Update jeromq to 0.6.0 (#1314)"
Seems some of its classes are a problem for the next commit's changes,
giving errors like:
```
Error:  error while loading SocketType,
Error:  class file org/zeromq/SocketType.class is broken, reading aborted with class java.lang.RuntimeException
Error:  bad constant pool index: 0 at pos: 1840
Error:  -- [E006] Not Found Error: /home/runner/work/almond/almond/modules/shared/channels/src/main/scala/almond/channels/zeromq/ZeromqSocketImpl.scala:20:14
Error:  20 |  socketType: SocketType,
Error:     |              ^^^^^^^^^^
Error:     |              Not found: type SocketType
Error:     |
Error:     | longer explanation available when compiling with `-explain`
```

This reverts commit e6dc050718b2877205ca89727de349d368e90191.